export const DATA_CONNECT_QUERIES = {
  GET_CURRENT_USER: 'GetCurrentUser',
  GET_USER_BY_PHONE: 'GetUserByPhone',
  GET_BRANCHES: 'GetBranches',
  GET_BRANCH_DETAILS: 'GetBranchDetails',
  GET_USERS_BY_ROLE: 'GetUsersByRole',
  GET_ASSIGNMENT_CONFLICTS: 'GetAssignmentConflicts',
  GET_GLOBAL_CLASSES: 'GetGlobalClasses',
  GET_CLASS_DETAILS: 'GetClassDetails',
  GET_GLOBAL_STUDENTS: 'GetGlobalStudents',
  GET_STUDENT_PROFILE: 'GetStudentProfile',
  GET_STUDENT_ATTENDANCE: 'GetStudentAttendance',
  GET_STUDENT_FEE_HISTORY: 'GetStudentFeeHistory',
  GET_DASHBOARD_STATISTICS: 'GetDashboardStatistics',
  GET_WINGS_BY_BRANCH: 'GetWingsByBranch',
  GET_CLASSES_BY_WING: 'GetClassesByWing',
  GET_SECTIONS_BY_CLASS: 'GetSectionsByClass',
  GET_TEACHER_ASSIGNMENTS: 'GetTeacherAssignments',
  SEARCH_STUDENTS: 'SearchStudents',
  GET_STUDENT_ID_SEQUENCE: 'GetStudentIdSequence',
  GET_STUDENTS_BY_BRANCH: 'GetStudentsByBranch',
  GET_STUDENTS_BY_SECTION: 'GetStudentsBySection',
  GET_PARENT_CHILDREN: 'GetParentChildren',
  GET_PARENT_BY_USER: 'GetParentByUser',
  GET_ATTENDANCE_BY_MONTH: 'GetAttendanceByMonth',
  GET_ATTENDANCE_BY_SECTION: 'GetAttendanceBySection',
  GET_FEE_DETAILS: 'GetFeeDetails',
  GET_FEE_RECORDS_BY_BRANCH: 'GetFeeRecordsByBranch',
  GET_ALL_FEE_RECORDS: 'GetAllFeeRecords',
  GET_DUE_STUDENTS: 'GetDueStudents',
  GET_PAID_STUDENTS: 'GetPaidStudents',
  GET_BRANCH_ANALYTICS: 'GetBranchAnalytics',
  GET_CLASS_ANALYTICS: 'GetClassAnalytics',
};

export const DATA_CONNECT_MUTATIONS = {
  CREATE_BRANCH: 'CreateBranch',
  UPDATE_BRANCH: 'UpdateBranch',
  ASSIGN_BRANCH_ADMIN: 'AssignBranchAdmin',
  ASSIGN_PRINCIPAL: 'AssignPrincipal',
  CREATE_CLASS: 'CreateClass',
  CREATE_SECTION: 'CreateSection',
  REMOVE_SECTION: 'RemoveSection',
  CREATE_USER: 'CreateUser',
  CLAIM_USER_FIREBASE_UID: 'ClaimUserFirebaseUID',
  CREATE_PARENT: 'CreateParent',
  CREATE_PARENT_WITHOUT_USER: 'CreateParentWithoutUser',
  CREATE_STUDENT: 'CreateStudent',
  CREATE_ATTENDANCE: 'CreateAttendance',
  UPDATE_ATTENDANCE: 'UpdateAttendance',
  UPLOAD_FEE_PAYMENT: 'UploadFeePayment',
  ASSIGN_TEACHER: 'AssignTeacher',
};
